name: Relex Scanner Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # بۆ ئەوەی هەر ٦ کاتژمێر جارێک ڕیستارت ببێتەوە و نەوەستێت

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyTelegramBotAPI requests

    - name: Run Bot
      run: python main1.py
      
